### ISSUE TITLE
Deps tracking

### ISSUE THREAD

**Issue by nado** [nado/nadoverlay#1]
# Remaining needed dependencies for check-all-the-things
## Unchecked
- [ ] debian
  - [ ] cme-check-dpkg
  - [ ] scan-copyrights
  - [ ] uscan
  - [ ] duck
  - [ ] lintian
  - [ ] lintian-curdir
  - [ ] lintian4python
  - [ ] upstream-metadata
  - [ ] wrap-and-sort
  - [ ] license-reconcile
  - [ ] debmake-k
  - [ ] licensecheck2dep5
  - [ ] autodep8
  - [ ] debian-tracker
- [ ] go
  - [ ] gofmt
## Ebuild needed
- [ ] android
  - [ ] android-lint
- [ ] appstream
  - [ ] appstreamcli-validate
- [ ] build-logs
  - [ ] blhc
  - [ ] bls-standalone
- [ ] chef
  - [ ] foodcritic
- [x] cypher
  - [x] cypher-lint
- [ ] elf
  - [ ] bfbtester
  - [ ] lockdep
  - [ ] zzuf
  - [ ] afl
  - [ ] hardening-check
- [ ] english
  - [ ] codespell
  - [ ] spellintian
- [ ] epub
  - [ ] epubcheck
  - [ ] flightcrew
- [ ] fonts
  - [ ] ftvalid
- [ ] gettext
  - [ ] gettext-lint-checker
  - [ ] gettext-lint-spell
  - [ ] i18nspector
- [ ] haskell
  - [ ] stylish-haskell : ebuild needed
- [ ] http
  - [ ] httpolice
- [ ] java
  - [ ] jlint
- [ ] javascript
  - [ ] librejs-cli
- [ ] jpeg2000
  - [ ] jpylyzer
- [ ] lua
  - [ ] luacheck
- [ ] misc
  - [ ] licensecheck
  - [ ] suspicious-source
  - [ ] autoupdate
  - [ ] autoscan
  - [ ] isutf8
  - [ ] embed-readme
  - [ ] embed-dirs
- [ ] mp3
  - [ ] checkmp3
  - [ ] mp3val
- [ ] ocaml
  - [ ] ocaml-lintian
- [ ] ogg
  - [ ] oggz-validate
- [ ] openpgp
  - [ ] hokey-lint
  - [ ] hokey-lint-asc
- [ ] perl
  - [ ] podlint
  - [ ] cpants-lint
- [ ] php
  - [ ] php-syntax-check
- [ ] rpm
  - [ ] rpmlint
- [ ] tex
  - [ ] lacheck
  - [ ] lintex
- [ ] x509
  - [ ] ssl-cert-check
- [ ] xapian
  - [ ] xapian-check
- [ ] yaml
  - [ ] yamllint

**Comment by nado** [comment]
Writing TODO in ebuild is easier.
